# Generated by Django 4.2 on 2023-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_bookflight_findflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookflight',
            name='email',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookflight',
            name='customer_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookflight',
            name='phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookflight',
            name='seat_id',
            field=models.CharField(max_length=500),
        ),
    ]
